#! /bin/sh
# this script is run by bootstrap.sh

# co = checkout
git config --global alias.co checkout
# st = status
git config --global alias.st 'status'
# cm = commit -v
git config --global alias.cm 'commit -v'
# df = diff 
git config --global alias.df 'diff'
# br = branch
git config --global alias.br 'branch'
# brm = branch --merged
git config --global alias.brm 'branch --merged'
# brn = branch --no-merged
git config --global alias.brn 'branch --no-merged'
# plr = pull --rebase 
git config --global alias.plr 'pull --rebase'
# lgp = log --graph --branches --pretty=format:'%d [%h] \"%s\"'
git config --global alias.logp 'log --graph --branches --pretty=format:"%d [%h] \"%s\""'
# st = status -sb    
git config --global alias.st 'status -sb'

# utils
# showremote = remote -v
git config --global alias.showremote 'remote -v'
