#! /bin/sh
# this script is run by bootstrap.sh

# a = add
git config --global alias.a add
# co = checkout
git config --global alias.co checkout
# co with peco
git config --global alias.pco '!git branch -a | peco | xargs git co'
# st = status
git config --global alias.st 'status'
# cm = commit -v
git config --global alias.cm 'commit -v'
# ac = add . && commit
git config --global alias.ac '!git add -A && git commit'
# df = diff
git config --global alias.df 'diff'
# br = branch
git config --global alias.br 'branch'
# brm = branch --merged
git config --global alias.brm 'branch --merged'
# brn = branch --no-merged
git config --global alias.brn 'branch --no-merged'
# plr = pull --rebase
git config --global alias.plr 'pull --rebase'
# lgp = log --graph --branches --pretty=format:'%d [%h] \"%s\"'
git config --global alias.logp 'log --graph --branches --pretty=format:"%d [%h] \"%s\""'
# st = status -sb
git config --global alias.st 'status -sb'

# utils
# showremote = remote -v
git config --global alias.showremote 'remote -v'
# dbranch = delete all merged branches
git config --global alias.dbranch 'branch --merged | grep -vE "^\*|master$|develop$" | xargs -I % git branch -d %'
