#! /bin/zsh

# open a remote by browser
openremote() {
  if [ $# -eq 0 ]
  then
    git remote show "origin" | grep Fetch | cut -d ":" -f2 -f3 | cut -d "." -f1 -f2 | xargs python -mwebbrowser
  else
    git remote show ${1} | grep Fetch | cut -d ":" -f2 -f3 | cut -d "." -f1 -f2 | xargs python -mwebbrowser
  fi
}
