autoload -Uz add-zsh-hook

####################
#    oh-my-zsh     #
####################

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# zsh theme
# List: ~/.oh-my-zsh/themes/
ZSH_THEME="avit"

# display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# plugins (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh


####################
# my configuration #
####################

# Base Directory Specification
export CONFIG_HOME="$HOME/dotfiles"
export ZSH_CONFIG="$CONFIG_HOME/zsh"

# Import zsh config files
source "$ZSH_CONFIG/aliases.zsh"
source "$ZSH_CONFIG/exports.zsh"
source "$ZSH_CONFIG/functions.zsh"

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Show Ruby version of rbenv
rbenv_version () {
  if [[ "`rbenv version | grep '.rbenv/version'`" = "" ]];then
    if [[ "`rbenv version | grep 'RBENV_VERSION'`" = "" ]];then
      local setting="L"
    else
      local setting="V"
    fi
  else
    local setting="G"
  fi
  RPROMPT="☕  `rbenv version | cut -f1 -d' '`($setting)"
}
add-zsh-hook precmd rbenv_version

# ls when changing directory
cdls ()
{
    \cd "$@" && ls
}
alias cd="cdls"

# history shortcut with peco
function peco-select-history() {
  local tac
  if which tac > /dev/null; then
    tac="tac"
  else
    tac="tail -r"
  fi
  if [ -n "$LBUFFER" ]; then
    BUFFER=$(\history -n 1 | \
      eval $tac | \
      ~/.go/bin/peco --query "$LBUFFER")
  else
    BUFFER=$(\history -n 1 | \
      eval $tac | \
      ~/.go/bin/peco)
  fi
  CURSOR=$#BUFFER
  zle clear-screen
}
zle -N peco-select-history
bindkey '^r' peco-select-history

# source zsh-syntax-highlighting
if [ -f ~/dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source ~/dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# back transition to directory
. $HOME/.zsh/plugins/bd/bd.zsh

# autojump prefix
if [ -f /usr/local/Cellar/autojump/22.2.4/share/autojump/autojump.zsh ]; then
  source /usr/local/Cellar/autojump/22.2.4/share/autojump/autojump.zsh
fi

echo "                     "
echo "                     "
echo "      ~-_  Enjoy     "
echo "     _-~     Coding! "
echo "   c|_|              "
echo "                     "
